import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://golfthehighsierra.com';
  const now = new Date().toISOString();

  const staticPages: MetadataRoute.Sitemap = [
    { url: `${base}/`, lastModified: now, changeFrequency: 'weekly', priority: 1.0 },
    { url: `${base}/about-group-golf-packages/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/accommodations-in-reno-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/best-golf-courses-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/best-golf-courses-lake-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/best-restaurants-reno-nv/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/blog-explore-the-high-sierra/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/cancellation-policy/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/contact-custom-golf-package/`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/corporate-golf-events/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/disclaimer-policy/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/experiences-things-to-do-in-reno-nv/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/faq/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/group-golf-lodging-packages/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/group-golf-reno-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/locations-map/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/new-golf-the-high-sierra-website/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/packages/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/privacy-policy/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/reno-golf-packages/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/lake-tahoe-golf-packages/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/terms-and-conditions/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/trip-builder/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${base}/trips-caddie-app/`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
  ];

  const taxonomyPages: MetadataRoute.Sitemap = [
    { url: `${base}/project-type/all-experiences/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/food/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-atlantis/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-carson-valley-inn/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-cedar-house/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-eldorado/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-lake-tahoe-resort/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/old-greenwood/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-golf-courses/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-golf-courses-page-2/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-golf-courses-page-3/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-hotels/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-hotels-page-2/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-hotels-page-3/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${base}/project-type/all-experiences-page-2/`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
  ];

  const coursePages: MetadataRoute.Sitemap = [
    { url: `${base}/portfolio/arrowcreek-golf-club/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/coyote-moon-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/dayton-valley-golf-club/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/eagle-valley-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/edgewood-tahoe-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/genoa-lakes-golf-club/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/graeagle-meadows-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/grays-crossing-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/grizzly-ranch-golf-club/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/incline-village-golf-courses-nv/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/lakeridge-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/nakoma-dragon-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/northstar-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/old-greenwood-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/plumas-pines-golf-resort/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/red-hawk-golf-resort/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/somersett-golf-country-club/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/tahoe-donner-golf-course-truckee-ca/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/toiyabe-golf-club/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/washoe-county-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/whitehawk-ranch-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/wolf-run-golf-club/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/winchester-golf-country-club/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/poppy-hills-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/bayonet-black-horse-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/lake-tahoe-golf-course/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
  ];

  const hotelPages: MetadataRoute.Sitemap = [
    { url: `${base}/portfolio/atlantis-casino-resort-spa-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/peppermill-resort-spa-casino/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/grand-sierra-resort-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/silver-legacy-resort-casino/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/eldorado-resorts-reno-eldorado-at-the-row/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/nugget-casino-resort-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/circus-circus-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/j-resort-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/hyatt-lake-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/harrahs-lake-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/harveys-lake-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/lake-tahoe-resort-hotel/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/golden-nugget-lake-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/margaritaville-lake-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/hampton-inn-truckee-ca/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/old-greenwood-lodging-truckee-ca/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/cedar-house-sport-hotel/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/carson-valley-inn-casino/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/plumas-pines-private-residency-graeagle/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/river-pines-resort-graeagle-ca/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/nakoma-resort-graeagle-ca/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/chalet-view-lodge-graeagle-ca/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/portfolio/portola-hotel-spa-monterey/`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
  ];

  const venuePages: MetadataRoute.Sitemap = [
    { url: `${base}/portfolio/chapel-tavern-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/lead-dog-brewing-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/the-emerson-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/the-eddy-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/rum-sugar-lime-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/death-and-taxes-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/pignic-pub-and-patio-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/scheels-sparks/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/outlets-at-legends-sparks/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/national-automobile-museum-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/nevada-museum-of-art-reno/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/spa-at-silver-legacy/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/reflections-the-spa-nugget/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/cliche-lounge-harrahs-tahoe/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/cabaret-lounge-carson-valley-inn/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/the-highlander-bar/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/silver-legacy-sports-bar/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/silver-baron-lounge/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/rum-bullions-island-bar/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/drinx-silver-legacy/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/comedy-bar-silver-legacy/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/blender-bar-silver-legacy/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/stadium-bar-eldorado/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/ringside-bar-eldorado/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/peppermill-sports-bar/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/carson-valley-inn-amenities/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/harveys-heated-pool/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/harveys-fitness-center/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/players-corner-spa-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-roxy/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-la-strada/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-brew-brothers/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-millies/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-ichiban/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-sushi-sake/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-hidden-pizza/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-coffee-company/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-starbucks/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-bar-centro/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-cin-cin/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-virginia-petite-1-queen/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-virginia-deluxe-2-queens/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-skyline-superior-1-king/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-skyline-superior-2-queens/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-skyline-deluxe-1-king/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-sierra-luxury-1-king/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-sierra-luxury-2-queen/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-sierra-studio-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-sierra-executive-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-corner-spa-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-spa-one-bedroom-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-skyline-player-spa-small/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-skyline-player-spa-large/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-skyline-vip-hospitality/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/eldorado-virginia-twenty-one-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-tower-room/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-luxury-tower-room/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-concierge-tower-room/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-spa-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-executive-spa-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-bar-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-atrium-paradise-suite/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-steakhouse/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-sports-bar-lounge/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${base}/portfolio/atlantis-cocktail-lounge/`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
  ];

  return [...staticPages, ...taxonomyPages, ...coursePages, ...hotelPages, ...venuePages];
}
